name:                PFP-JUN06
version:             0.2.0.0
synopsis:            Probabalistic Functions
license:             NCSA

description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- parsec
- random
- mtl
- MissingH >= 1.4.3.0
- transformers
- containers

library:
  source-dirs: src


executables:
  PFP-JUN06:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFP-JUN06
    - hspec

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck >= 2.9.0
    - HUnit >= 1.5
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-io
    default-extensions:
    - NamedFieldPuns
